import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/navbar/Navbar";
import LoginModal from "./Components/modals/LoginModal";
import SearchModal from "./Components/modals/SearchModal";
import SignupModal from "./Components/modals/SignupModal";
import AddPropertyModal from "./Components/modals/AddPropertyModal";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "DjangoBnb",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
    <p>Yo yo</p>
  )


  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />


        <div className="pt-32">
          {children}
        </div>


        <LoginModal />
        <SearchModal />
        <SignupModal />
        <AddPropertyModal />
      </body>
    </html>
  );
}
